### ISSUE TITLE
Replace detection of scorables?

### ISSUE THREAD

**Issue by otacke** [fnoks/h5p-mc#10]
https://github.com/fnoks/h5p-mc/blob/8a27ec86543116a5a5ea72c1a9ead44660a8d961/src/scripts/CourseUnit.js#L72

Could this be replaced by

```
if (typeof this.getInstance().getMaxScore === 'function' && this.getInstance().getMaxScore() > 0) {
```
??? If a maximum score larger than 0 can be achieved, an instance should be scorable, right? Or is there a reason for handling this using a hard coded list? There's no comment indicating why it might be used.

Having hard coded lists such as https://github.com/fnoks/h5p-mc/blob/8a27ec86543116a5a5ea72c1a9ead44660a8d961/src/scripts/CourseUnit.js#L6-L21 causes trouble quite frequently. 

Given the currently supported content types, there are only _Fill in the Blanks_ and _Column_ that would not get caught correctly:
- _Fill in the Blanks_ reports a maxScore of 0 before it is attached to the DOM, but [there's already a fix pending for this problem](https://github.com/h5p/h5p-blanks/pull/69).
- _Column_ is not inside that hardcoded list, although it reports the maxScore reliably (except for when it contains "Fill in the Blanks"), so I am not sure why it's excluded from the "scorables"

**Comment by fnoks** [comment]
I agree, @otacke . Please go ahead and do whatever change needed :)
